"""主机侧静态配置。"""

from .feetech import (
    END_EFFECTOR_ROTATION_CONFIG,
    END_EFFECTOR_ROTATION_DEFAULT_SPEED_RAW,
    END_EFFECTOR_ROTATION_POSITIVE_DIRECTION,
    FEETECH_MODEL_PROFILES,
    SM45BL_C001_PROFILE,
)
from .joints import (
    ELBOW_JOINT_CONFIG,
    JOINT_CONFIGS,
    SHOULDER_JOINT_CONFIG,
)


__all__ = [
    "ELBOW_JOINT_CONFIG",
    "END_EFFECTOR_ROTATION_CONFIG",
    "END_EFFECTOR_ROTATION_DEFAULT_SPEED_RAW",
    "END_EFFECTOR_ROTATION_POSITIVE_DIRECTION",
    "FEETECH_MODEL_PROFILES",
    "JOINT_CONFIGS",
    "SHOULDER_JOINT_CONFIG",
    "SM45BL_C001_PROFILE",
]
