"""统一异步点到点运动控制；硬件相关控制器按需延迟导入。"""

from motion.authorization import (
    MotionAuthorization,
    MotionAuthorizationError,
    RotationMotionAuthorizationError,
    RuntimeMode,
)
from motion.suction import (
    STM32SuctionControl,
    SuctionControl,
    SuctionMode,
    SuctionStatus,
)
from motion.unified_protocol import (
    ArrivalConfig,
    AxisCapabilities,
    AxisDescriptor,
    AxisKind,
    AxisName,
    AxisState,
    AxisTarget,
    MotionCommandHandle,
    MotionCommandResult,
    MotionCommandStatus,
    MotionErrorCode,
    MultiAxisCommandHandle,
    MultiAxisCommandResult,
    MultiAxisTarget,
    RelativeAxisTarget,
    RotaryJointEnableStatus,
    StopReport,
)

__all__ = [
    "ArrivalConfig",
    "AxisCapabilities",
    "AxisDescriptor",
    "AxisKind",
    "AxisName",
    "AxisState",
    "AxisTarget",
    "MotionAuthorization",
    "MotionAuthorizationError",
    "MotionCommandHandle",
    "MotionCommandResult",
    "MotionCommandStatus",
    "MotionErrorCode",
    "MultiAxisCommandHandle",
    "MultiAxisCommandResult",
    "MultiAxisTarget",
    "RelativeAxisTarget",
    "RotationMotionAuthorizationError",
    "RotaryJointEnableStatus",
    "StopReport",
    "RuntimeMode",
    "STM32SuctionControl",
    "SuctionControl",
    "SuctionMode",
    "SuctionStatus",
]
